// These values are safe to commit — they are public-facing URLs, not secrets.

// All booking/review platforms in one place.
// To add a platform: append one object below and set active: true when ready.
// bookingUrl → listing page (/book page); reviewUrl → review-request link (/review page).
export const PLATFORMS = [
  {
    id: 'airbnb',
    bookingUrl: 'https://www.airbnb.com/rooms/1653978699227724936',
    reviewUrl:  'https://www.airbnb.com/rooms/1653978699227724936/reviews',
    active: true,
  },
  {
    id: 'booking',
    bookingUrl: 'https://www.booking.com/hotel/pr/delrom-4-beds-entire-apartment.html',
    reviewUrl:  'https://www.booking.com/hotel/pr/delrom-4-beds-entire-apartment.html',
    active: true,
  },
  {
    id: 'vrbo',
    bookingUrl: 'https://www.vrbo.com/placeholder',
    reviewUrl: 'https://www.vrbo.com/placeholder',
    active: false,
  },
]

// Derived arrays — shape matches what platform-buttons.jsx expects. No need to edit these.
export const BOOKING_PLATFORMS = PLATFORMS.map((p) => ({ id: p.id, url: p.bookingUrl, active: p.active }))
export const REVIEW_PLATFORMS  = PLATFORMS.map((p) => ({ id: p.id, url: p.reviewUrl,  active: p.active }))

/**
 * Returns where "Book Now" CTAs should send the guest.
 * - One active platform → direct external link (no extra tap).
 * - Two or more → route to /book hub so the guest can choose.
 * @returns {{ type: 'external', url: string } | { type: 'hub' }}
 */
export function getBookingDestination() {
  const active = BOOKING_PLATFORMS.filter((p) => p.active)
  if (active.length === 1) return { type: 'external', url: active[0].url }
  return { type: 'hub' }
}

export const EMAIL = 'info@thedelrom.com'

// Testimonials from booking platforms
export const TESTIMONIALS = [
  {
    id: 1,
    author: 'Maribel',
    location: 'Phoenix, Arizona',
    platform: 'airbnb',
    rating: 5,
    text: 'testimonials.review1',
    date: '2024-05-20',
  },
  {
    id: 2,
    author: 'Dennis',
    location: 'United States',
    platform: 'booking',
    rating: 10,
    text: 'testimonials.review2',
    date: '2024-05-15',
  },
  {
    id: 3,
    author: 'Álvarez',
    location: 'Aguadilla, Puerto Rico',
    platform: 'airbnb',
    rating: 5,
    text: 'testimonials.review3',
    date: '2026-05-31',
  },
  // Add more testimonials as needed — just append to this array
]

/** Google Analytics 4 measurement ID (also in index.html gtag snippet). */
export const GA_MEASUREMENT_ID = 'G-C2FJN705N0'

// --- Map (Location section) -------------------------------------------------
// DelRom map: minimal, no street labels, brand colors (warmWhite / sand / terracotta pin).
//
// A) Google Static Maps (recommended — clean, no labels):
//    1. Google Cloud Console → enable "Maps Static API" (+ "Maps Embed API" optional).
//    2. Paste API key into GOOGLE_MAPS_EMBED_API_KEY below.
//    3. Set MAP_CENTER to your property. Static styled map is used automatically.
//
// B) No API key: paste Google Share → Embed src into MAPS_EMBED_SRC (standard Google Maps UI).

export const GOOGLE_MAPS_EMBED_API_KEY = ''

/** @deprecated — use MAP_CENTER + static map when API key is set */
export const MAPS_PLACE_QUERY = ''

/** Property coordinates for static map pin */
export const MAP_CENTER = { lat: 18.3969988, lng: -66.0364954 }

/** Opens full Google Maps when guest taps the map */
export const MAPS_OPEN_URL =
  'https://www.google.com/maps/place/425+C.+Soldado+Alcides+Reyes+de+Jes%C3%BAs,+San+Juan,+00923'

/** Used when GOOGLE_MAPS_EMBED_API_KEY is empty (Google Share → Embed src) */
export const MAPS_EMBED_SRC =
  'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4234.499495619105!2d-66.0390703244256!3d18.397003872936352!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c03662d092733ff%3A0xb680b135e055a2e5!2s425%20C.%20Soldado%20Alcides%20Reyes%20de%20Jes%C3%BAs%2C%20San%20Juan%2C%2000923!5e1!3m2!1sen!2spr!4v1779658491443!5m2!1sen!2spr'

const STATIC_MAP_STYLES = [
  'feature:all|element:labels|visibility:off',
  'feature:landscape|color:0xFAF8F4',
  'feature:water|color:0xE8DDD0',
  'feature:road|color:0xE8DDD0',
  'feature:road.highway|color:0xC4B5A0',
  'feature:poi|visibility:off',
  'feature:transit|visibility:off',
]

/**
 * Styled static map — no labels, DelRom palette. Requires Maps Static API + key.
 * @returns {string} image URL, or '' when no API key
 */
export function getStaticMapSrc(width = 640, height = 480) {
  const key = GOOGLE_MAPS_EMBED_API_KEY.trim()
  if (!key) return ''

  const { lat, lng } = MAP_CENTER
  const params = new URLSearchParams({
    center: `${lat},${lng}`,
    zoom: '16',
    size: `${width}x${height}`,
    scale: '2',
    key,
    markers: `color:0xC17A5A|${lat},${lng}`,
  })
  STATIC_MAP_STYLES.forEach((style) => params.append('style', style))
  return `https://maps.googleapis.com/maps/api/staticmap?${params.toString()}`
}

/** @returns {string} iframe src for embed fallback when static map unavailable */
export function getMapEmbedSrc() {
  return MAPS_EMBED_SRC.trim()
}

// --- Explore (Nearby Places) --------------------------------------------------

// --- Tren Urbano (route + stations) -----------------------------------------
// Mix of verified (Google Maps) and approximate coordinates.
// ⚠️  Stations without links still have estimates — update as you get real coordinates.
export const TREN_URBANO_STATIONS = [
  { id: 1,  name: 'Bayamón',          lat: 18.3969, lng: -66.1565, nearDelRom: false },
  { id: 2,  name: 'Deportivo',        lat: 18.3997, lng: -66.1403, nearDelRom: false },
  { id: 3,  name: 'Torrimar',         lat: 18.4028, lng: -66.1229, nearDelRom: false },
  { id: 4,  name: 'Universidad',      lat: 18.4058, lng: -66.05171, nearDelRom: false },
  { id: 5,  name: 'Jardines',         lat: 18.4087, lng: -66.1005, nearDelRom: false },
  { id: 6,  name: 'Las Lomas',        lat: 18.39079, lng: -66.09389, nearDelRom: false },
  { id: 7,  name: 'Martínez Nadal',   lat: 18.4098, lng: -66.0786, nearDelRom: false },
  { id: 8,  name: 'Cupey',            lat: 18.3905086, lng: -66.0631271, nearDelRom: false },
  { id: 9,  name: 'Domingo Colón',    lat: 18.3998, lng: -66.0632, nearDelRom: false },
  { id: 10, name: 'Centro Médico',    lat: 18.39152, lng: -66.07489, nearDelRom: false },
  { id: 11, name: 'Río Piedras',      lat: 18.39962, lng: -66.05214, nearDelRom: true  },
  { id: 12, name: 'UPR',              lat: 18.4058, lng: -66.05171, nearDelRom: true  },
  { id: 13, name: 'Hato Rey',         lat: 18.42944, lng: -66.06023, nearDelRom: false },
  { id: 14, name: 'Roosevelt',        lat: 18.4235097, lng: -66.0588799, nearDelRom: false },
  { id: 15, name: 'Domenech',         lat: 18.41561, lng: -66.05639, nearDelRom: false },
  { id: 16, name: 'Sagrado Corazón',  lat: 18.43671, lng: -66.06072, nearDelRom: false },
]

// featured: true  →  marks the location as a Host Pick in the explore map
// photo       →  swap placeholder URL for a real photo when ready
export const NEARBY_LOCATIONS = [
  // --- Dining ----------------------------------------------------------------
  {
    id: 1,
    name: 'Açaí Express',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.3950034,
    lng: -66.0374903,
    distance: '0.3 km',
    photo: 'https://picsum.photos/seed/acaiexpress/400/300',
    hours: 'Daily 10am–9pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/A%C3%A7a%C3%AD+Express/@18.3950034,-66.0374903',
  },
  {
    id: 2,
    name: 'El Rey del Mofongo',
    category: 'dining',
    type: 'dining',
    featured: true,
    lat: 18.3949374,
    lng: -66.0370528,
    distance: '0.5 km',
    photo: 'https://picsum.photos/seed/reydelmofongo/400/300',
    hours: 'Daily 11am–10pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/El+Rey+del+Mofongo/@18.3949374,-66.0370528',
  },
  {
    id: 3,
    name: 'Corazón Chino',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.3955066,
    lng: -66.0407917,
    distance: '0.4 km',
    photo: 'https://picsum.photos/seed/corazonchin/400/300',
    hours: 'Daily 12pm–11pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Coraz%C3%B3n+Chino/@18.3955066,-66.0407917',
  },
  {
    id: 4,
    name: 'McDonald\'s',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.394612,
    lng: -66.041256,
    distance: '0.6 km',
    photo: 'https://picsum.photos/seed/mcdonalds/400/300',
    hours: 'Daily 7am–11pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/McDonald\'s/@18.394612,-66.041256',
  },
  {
    id: 5,
    name: 'El Mesón Sandwiches',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.3968,
    lng: -66.0412,
    distance: '0.4 km',
    photo: 'https://picsum.photos/seed/meson/400/300',
    hours: 'Daily 6am–10pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/El+Meson+Sandwiches+Rio+Piedras+San+Juan+PR',
  },
  {
    id: 6,
    name: 'La Casita Blanca',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.4022,
    lng: -66.0546,
    distance: '2.1 km',
    photo: 'https://picsum.photos/seed/casita/400/300',
    hours: 'Wed–Sun 11am–4pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/La+Casita+Blanca+San+Juan+Puerto+Rico',
  },
  {
    id: 7,
    name: 'Kasalta Bakery',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.4048,
    lng: -66.0503,
    distance: '2.6 km',
    photo: 'https://picsum.photos/seed/kasalta/400/300',
    hours: 'Daily 6am–10pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Kasalta+Bakery+San+Juan+Puerto+Rico',
  },
  {
    id: 14,
    name: 'Subway',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.394384,
    lng: -66.0339743,
    distance: '0.2 km',
    photo: 'https://picsum.photos/seed/subway/400/300',
    hours: 'Daily 9am–10pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Subway/@18.394384,-66.0339743',
  },
  {
    id: 15,
    name: 'Subway Ave. 65 de Infantería',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.3939267,
    lng: -66.0339187,
    distance: '0.3 km',
    photo: 'https://picsum.photos/seed/subway65/400/300',
    hours: 'Daily 9am–10pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Subway+ave.+65+de+infantería/@18.3939267,-66.0339187',
  },
  {
    id: 16,
    name: 'La Península Panadería y Repostería',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.3943934,
    lng: -66.0371501,
    distance: '0.2 km',
    photo: 'https://picsum.photos/seed/lapeninsulabakery/400/300',
    hours: 'Daily 6am–8pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/La+Península+Panadería+y+Repostería/@18.3943934,-66.0371501',
  },
  {
    id: 17,
    name: 'Mimo\'s Pizza',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.3944194,
    lng: -66.0374456,
    distance: '0.2 km',
    photo: 'https://picsum.photos/seed/mimospizza/400/300',
    hours: 'Daily 11am–11pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Mimo\'s+Pizza/@18.3944194,-66.0374456',
  },
  {
    id: 18,
    name: 'Mofonbowl San Juan',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.3947015,
    lng: -66.0416592,
    distance: '0.3 km',
    photo: 'https://picsum.photos/seed/mofonbowl/400/300',
    hours: 'Daily 10am–11pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Mofonbowl+San+Juan+Rio+Piedras/@18.3947015,-66.0416592',
  },
  {
    id: 19,
    name: 'El Obrero',
    category: 'dining',
    type: 'dining',
    featured: false,
    lat: 18.4003188,
    lng: -66.0431908,
    distance: '0.8 km',
    photo: 'https://picsum.photos/seed/elobrero/400/300',
    hours: 'Daily 11am–10pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/El+Obrero/@18.4003188,-66.0431908',
  },
  // --- Beaches ---------------------------------------------------------------
  {
    id: 14,
    name: 'Ocean Park Beach',
    category: 'beaches',
    type: 'beaches',
    featured: true,
    lat: 18.4056,
    lng: -66.0476,
    distance: '2.8 km',
    photo: 'https://picsum.photos/seed/oceanpark/400/300',
    hours: 'Always open',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Ocean+Park+Beach+San+Juan+Puerto+Rico',
  },
  {
    id: 15,
    name: 'Escambrón Beach',
    category: 'beaches',
    type: 'beaches',
    featured: false,
    lat: 18.4601,
    lng: -66.0768,
    distance: '5.1 km',
    photo: 'https://picsum.photos/seed/escambron/400/300',
    hours: 'Daily 8am–5pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Escambrón+Beach+San+Juan+Puerto+Rico',
  },
  {
    id: 16,
    name: 'Isla Verde Beach',
    category: 'beaches',
    type: 'beaches',
    featured: false,
    lat: 18.4493,
    lng: -65.9878,
    distance: '7.4 km',
    photo: 'https://picsum.photos/seed/islaverde/400/300',
    hours: 'Always open',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Isla+Verde+Beach+Carolina+Puerto+Rico',
  },
  // --- Shopping --------------------------------------------------------------
  {
    id: 17,
    name: '65 de Infantería Shopping Center',
    category: 'shopping',
    type: 'shopping',
    featured: true,
    lat: 18.3955231,
    lng: -66.0415209,
    distance: '0.5 km',
    photo: 'https://picsum.photos/seed/infanteria/400/300',
    hours: 'Mon–Sat 9am–9pm, Sun 11am–8pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/65+de+Infanter%C3%ADa+Shopping+Center/@18.3955231,-66.0415209',
  },
  {
    id: 18,
    name: 'Banco Popular Shopping',
    category: 'shopping',
    type: 'shopping',
    featured: false,
    lat: 18.395497,
    lng: -66.041157,
    distance: '0.6 km',
    photo: 'https://picsum.photos/seed/bancopop/400/300',
    hours: 'Mon–Sat 9am–8pm, Sun 11am–7pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Banco+Popular/@18.395497,-66.041157',
  },
  {
    id: 19,
    name: 'Plaza Las Américas',
    category: 'shopping',
    type: 'shopping',
    featured: false,
    lat: 18.3912,
    lng: -66.0596,
    distance: '2.2 km',
    photo: 'https://picsum.photos/seed/plazalas/400/300',
    hours: 'Mon–Sat 9am–9pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Plaza+Las+Americas+San+Juan+Puerto+Rico',
  },
  {
    id: 20,
    name: 'Mercado de Río Piedras',
    category: 'shopping',
    type: 'shopping',
    featured: false,
    lat: 18.3984,
    lng: -66.0357,
    distance: '0.3 km',
    photo: 'https://picsum.photos/seed/mercado/400/300',
    hours: 'Mon–Sat 6am–6pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Mercado+Municipal+Rio+Piedras+San+Juan+PR',
  },
  {
    id: 26,
    name: 'Mobil Gas Station',
    category: 'shopping',
    type: 'shopping',
    subtype: 'shopping',
    featured: false,
    lat: 18.3944375,
    lng: -66.0340625,
    distance: '0.2 km',
    photo: 'https://picsum.photos/seed/mobilgas/400/300',
    hours: 'Daily 6am–11pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Mobil+Gas+Station/@18.3944375,-66.0340625',
  },
  {
    id: 27,
    name: 'TotalEnergies San Agustín',
    category: 'shopping',
    type: 'shopping',
    subtype: 'shopping',
    featured: false,
    lat: 18.3946637,
    lng: -66.0408311,
    distance: '0.3 km',
    photo: 'https://picsum.photos/seed/totalenergies/400/300',
    hours: 'Daily 6am–11pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/TotalEnergies+San+Agustín/@18.3946637,-66.0408311',
  },
  {
    id: 28,
    name: 'Supermercados Plaza Loíza - 65th Infantería',
    category: 'shopping',
    type: 'shopping',
    featured: false,
    lat: 18.3960288,
    lng: -66.0412966,
    distance: '0.5 km',
    photo: 'https://picsum.photos/seed/plazaloiza/400/300',
    hours: 'Daily 8am–9pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Supermercados+Plaza+Loíza+-+65th+Infantería/@18.3960288,-66.0412966',
  },
  {
    id: 29,
    name: 'Walgreens Photo',
    category: 'shopping',
    type: 'shopping',
    featured: false,
    lat: 18.39618,
    lng: -66.041722,
    distance: '0.5 km',
    photo: 'https://picsum.photos/seed/walgreens/400/300',
    hours: 'Daily 8am–9pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Walgreens+Photo/@18.39618,-66.041722',
  },
  {
    id: 30,
    name: 'Farmacia Medina #5',
    category: 'shopping',
    type: 'shopping',
    subtype: 'shopping',
    featured: false,
    lat: 18.3976127,
    lng: -66.0334714,
    distance: '0.2 km',
    photo: 'https://picsum.photos/seed/farmacimedina/400/300',
    hours: 'Daily 8am–9pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Farmacia+Medina+%235/@18.3976127,-66.0334714',
  },
  // --- Attractions -----------------------------------------------------------
  {
    id: 26,
    name: 'Old San Juan',
    category: 'attractions',
    type: 'attractions',
    featured: false,
    lat: 18.4660,
    lng: -66.1180,
    distance: '9.3 km',
    photo: 'https://picsum.photos/seed/oldsanjuan/400/300',
    hours: 'Always open',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Old+San+Juan+Puerto+Rico',
  },
  {
    id: 27,
    name: 'Castillo San Felipe del Morro',
    category: 'attractions',
    type: 'attractions',
    featured: false,
    lat: 18.4708,
    lng: -66.1242,
    distance: '9.8 km',
    photo: 'https://picsum.photos/seed/elmorro/400/300',
    hours: 'Daily 9am–6pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Castillo+San+Felipe+del+Morro+Puerto+Rico',
  },
  // --- Nightlife -------------------------------------------------------------
  {
    id: 28,
    name: 'La Factoría',
    category: 'nightlife',
    type: 'nightlife',
    featured: true,
    lat: 18.4661,
    lng: -66.1175,
    distance: '9.3 km',
    photo: 'https://picsum.photos/seed/factoria/400/300',
    hours: 'Wed–Sun 6pm–2am',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/La+Factoria+Old+San+Juan+Puerto+Rico',
  },
  {
    id: 29,
    name: 'Calle Loíza',
    category: 'nightlife',
    type: 'nightlife',
    featured: false,
    lat: 18.4014,
    lng: -66.0551,
    distance: '2.4 km',
    photo: 'https://picsum.photos/seed/calleloiza/400/300',
    hours: 'Daily 6pm–2am',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Calle+Loiza+San+Juan+Puerto+Rico',
  },

  // --- Emergency -------------------------------------------------------------
  // ⚠️  Verify these coordinates on Google Maps before going live
  {
    id: 30,
    name: 'Hospital San Francisco',
    category: 'emergency',
    type: 'emergency',
    featured: true,
    lat: 18.3987918,
    lng: -66.038981,
    distance: '0.3 km',
    photo: 'https://picsum.photos/seed/hospitalsanfran/400/300',
    hours: '24 hours',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Hospital+San+Francisco/@18.3987918,-66.038981',
  },
  {
    id: 31,
    name: 'Policía de Puerto Rico – Monte Hatillo',
    category: 'emergency',
    type: 'emergency',
    featured: false,
    lat: 18.3951455,
    lng: -66.0353195,
    distance: '0.2 km',
    photo: 'https://picsum.photos/seed/policia/400/300',
    hours: 'Always open',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Polic%C3%ADa+de+Puerto+Rico+-+Precinto+Monte+Hatillo/@18.3951455,-66.0353195',
  },
  {
    id: 32,
    name: 'Bomberos – Estación Río Piedras',
    category: 'emergency',
    type: 'emergency',
    featured: false,
    lat: 18.3978,
    lng: -66.0425,
    distance: '0.5 km',
    photo: 'https://picsum.photos/seed/bomberos/400/300',
    hours: 'Always open',
    phone: '787-343-2330',
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/search/Bomberos+Rio+Piedras+San+Juan+PR',
  },

  // --- Transit ---------------------------------------------------------------
  // Mix of verified (Google Maps) and approximate coordinates.
  {
    id: 33,
    name: 'Tren Urbano – Río Piedras',
    category: 'transit',
    type: 'transit',
    featured: true,
    lat: 18.39962,
    lng: -66.05214,
    distance: '0.8 km',
    photo: 'https://picsum.photos/seed/trenurbano/400/300',
    hours: 'Daily 5:30am–11:30pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/R%C3%ADo+Piedras/@18.39962,-66.05214',
  },
  {
    id: 34,
    name: 'Tren Urbano – UPR',
    category: 'transit',
    type: 'transit',
    featured: false,
    lat: 18.4058,
    lng: -66.05171,
    distance: '1.3 km',
    photo: 'https://picsum.photos/seed/trenurbanoupr/400/300',
    hours: 'Daily 5:30am–11:30pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Universidad/@18.4058,-66.05171',
  },
  {
    id: 35,
    name: 'Tren Urbano – Centro Médico',
    category: 'transit',
    type: 'transit',
    featured: false,
    lat: 18.39152,
    lng: -66.07489,
    distance: '0.5 km',
    photo: 'https://picsum.photos/seed/trencentromedico/400/300',
    hours: 'Daily 5:30am–11:30pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Medical+Center/@18.39152,-66.07489',
  },
  {
    id: 36,
    name: 'Tren Urbano – Cupey',
    category: 'transit',
    type: 'transit',
    featured: false,
    lat: 18.3905086,
    lng: -66.0631271,
    distance: '1.1 km',
    photo: 'https://picsum.photos/seed/trencupey/400/300',
    hours: 'Daily 5:30am–11:30pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Cupey/@18.3905086,-66.0631271',
  },
  {
    id: 37,
    name: 'Tren Urbano – Las Lomas',
    category: 'transit',
    type: 'transit',
    featured: false,
    lat: 18.39079,
    lng: -66.09389,
    distance: '2.1 km',
    photo: 'https://picsum.photos/seed/trenlaslomas/400/300',
    hours: 'Daily 5:30am–11:30pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Las+Lomas/@18.39079,-66.09389',
  },
  {
    id: 38,
    name: 'Tren Urbano – Hato Rey',
    category: 'transit',
    type: 'transit',
    featured: false,
    lat: 18.42944,
    lng: -66.06023,
    distance: '3.2 km',
    photo: 'https://picsum.photos/seed/trenhatohey/400/300',
    hours: 'Daily 5:30am–11:30pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Hato+Rey/@18.42944,-66.06023',
  },
  {
    id: 39,
    name: 'Tren Urbano – Roosevelt',
    category: 'transit',
    type: 'transit',
    featured: false,
    lat: 18.4235097,
    lng: -66.0588799,
    distance: '3.6 km',
    photo: 'https://picsum.photos/seed/trenroosevelt/400/300',
    hours: 'Daily 5:30am–11:30pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Roosevelt/@18.4235097,-66.0588799',
  },
  {
    id: 40,
    name: 'Tren Urbano – Sagrado Corazón',
    category: 'transit',
    type: 'transit',
    featured: false,
    lat: 18.43671,
    lng: -66.06072,
    distance: '4.2 km',
    photo: 'https://picsum.photos/seed/trensagradocorazon/400/300',
    hours: 'Daily 5:30am–11:30pm',
    phone: null,
    website: null,
    googleMapsUrl: 'https://www.google.com/maps/place/Sagrado+Coraz%C3%B3n/@18.43671,-66.06072',
  },
]
